name: Kubewarden Policy Catalog Release

on:
  workflow_call:
    inputs:
      policy-name:
        description: "The name of the policy. This is used in monorepos where multiple policies can be released"
        required: false
        type: string
      policy-working-dir:
        description: "Working directory of the policy. Useful for repos with policies in folders"
        required: false
        type: string
        default: "."
    secrets:
      APP_ID:
        description: "GitHub App ID used to generate a token for the repository dispatch"
        required: true
      APP_PRIVATE_KEY:
        description: "GitHub App Private Key used to generate a token for the repository dispatch"
        required: true

jobs:
  release-catalog:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # Set the owner, so the token can be used for cross-repo dispatch
          owner: ${{ github.repository_owner }}
      - name: Prepare catalog payload
        id: catalog-payload
        run: |
          PAYLOAD='{
            "owner": "${{ github.repository_owner }}",
            "repo": "${{ github.event.repository.name }}",
            "tag": "${{ github.ref_name }}"
          }'

          if [ -n "${{ inputs.policy-name }}" ]; then
            PAYLOAD=$(echo $PAYLOAD | jq '. + {"chart_dir": "${{ inputs.policy-name }}"}')
          fi

          if [ "${{ inputs.policy-working-dir }}" != "." ]; then
            PAYLOAD=$(echo $PAYLOAD | jq '. + {"artifacthub_pkg_path": "${{ inputs.policy-working-dir }}/artifacthub-pkg.yml"}')
          fi

          echo "payload=$(echo $PAYLOAD | jq -c)" >> $GITHUB_OUTPUT
      - name: Release policy catalog
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: kubewarden/policy-catalog
          event-type: release-policy
          client-payload: ${{ steps.catalog-payload.outputs.payload }}
