name: Build and release a Kubewarden policy written in Rust

on:
  workflow_call:
    inputs:
      input-wasm:
        type: string
        required: true
      oci-target:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v1
      -
        name: Build and annotate policy
        uses: kubewarden/github-actions/policy-build-rust@v1
        with:
          input-wasm: target/wasm32-wasi/release/${{ inputs.input-wasm }}.wasm
      -
        name: Run e2e tests
        run: |
          make e2e-tests
      -
        name: Release
        uses: kubewarden/github-actions/policy-release@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          oci-target: ${{ inputs.oci-target }}
          annotated-wasm: annotated-policy.wasm

